import type { APIRoute } from 'astro';

// Serves /sw.js. Prerendered at build, so the version below is baked in per build.
export const prerender = true;

// CACHE_NAME must change on every deploy so the `activate` handler purges the old
// cache and every returning client gets fresh assets. Prefer the Vercel commit SHA
// (stable per commit); fall back to a build timestamp locally / off-Vercel.
const commitSha =
  (import.meta as unknown as { env?: Record<string, string | undefined> }).env
    ?.VERCEL_GIT_COMMIT_SHA ??
  (globalThis as unknown as { process?: { env?: Record<string, string | undefined> } })
    .process?.env?.VERCEL_GIT_COMMIT_SHA;
const BUILD_VERSION = (commitSha && commitSha.slice(0, 8)) ||
  new Date().toISOString().slice(0, 19).replace(/[-:T]/g, '');

const SW = `// Auto-generated by src/pages/sw.js.ts — do not edit by hand.
// Cache version is stamped at build time so each deploy invalidates the old cache.
const CACHE_NAME = 'formiche-${BUILD_VERSION}';
const PRECACHE_URLS = [
  '/',
  '/identifica/',
  '/generi/',
  '/esperti/',
  '/anatomia/',
  '/manifest.json',
  '/images/placeholder-ant.svg',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  if (!url.protocol.startsWith('http')) return;

  const isNavigation =
    event.request.mode === 'navigate' ||
    (event.request.headers.get('accept') || '').includes('text/html');

  if (isNavigation) {
    // Network-first for HTML: always serve the freshest page online (so it references
    // the current hashed JS/CSS), falling back to cache only when offline.
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          // SECURITY: only cache valid, same-origin, successful responses.
          if (response.ok && response.type === 'basic' && response.status === 200) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
          }
          return response;
        })
        .catch(() =>
          caches.match(event.request).then((cached) => cached || caches.match('/'))
        )
    );
    return;
  }

  // Cache-first for other assets: JS/CSS are content-hashed (a new build = new URL),
  // images are stable, so a cache hit is always safe within a cache version.
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (response.ok && response.type === 'basic' && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
        }
        return response;
      });
    })
  );
});
`;

export const GET: APIRoute = () =>
  new Response(SW, {
    headers: {
      'Content-Type': 'text/javascript; charset=utf-8',
      'Cache-Control': 'no-cache',
    },
  });
